---
- name: Setup NTP
  hosts: all
  tasks:
  - name: Install Chrony
    dnf:
      name: chrony
      state: latest
  - name: Copy Chrony config file
    copy:
      src: chrony.conf
      dest: /etc/chrony.conf
  - name: Restart Chrony
    service:
      name: chronyd
      state: restarted
  - name: Enable Chrony
    service:
      name: chronyd
      enabled: yes
